import { auth } from '@/auth.config';
import type { Metadata } from "next";
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: "Login Information",
  description: "Generated by create next app",
};

export default async function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {

  const session = await auth();

  // redireccionar al usuario si esta autenticado
  if ( session?.user ) {
    redirect( '/admin' );
  }

  return (
    <main>
      { children }
    </main>
  );
}
