import type { Metadata } from "next";
import "../app/assets/scss/tailwind.scss";
import './assets/css/material.css';
import { alex, eb_garamond, kaushan, nunito, work_sans } from '@/config/font';

export const metadata: Metadata = {
  title: "Information",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en" dir="LTR">
      <body
        className={ `${ nunito.variable } ${ work_sans.variable } ${ eb_garamond.variable } ${ kaushan.variable } ${ alex.variable } font-nunito text-base` }
      >
        { children }
      </body>
    </html>
  );
}
