import '../globals.css';
import "../assets/css/tailwind.css";
import '../assets/css/materialdesignicons.min.css';
import type { Metadata } from "next";
import { auth } from '@/auth.config';
import { redirect } from 'next/navigation';
import { Provider } from '@/components';

export const metadata: Metadata = {
  title: "Information Admin",
  description: "Generated by create next app",
};

export default async function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {

  const session = await auth();
  console.log( session );


  if ( !session?.user ) {
    redirect( '/auth/login' ); // Si no existe la sesión, redirigir a la página de login
  }

  return (
    <Provider>
      { children }
    </Provider>
  );
}
