import type { Metadata } from "next";
import "../assets/scss/tailwind.scss";
import '../assets/css/material.css';
import { alex, eb_garamond, kaushan, nunito, work_sans } from '@/config/font';
import { auth } from '@/auth.config';
import { redirect } from 'next/navigation';
import { Provider } from '@/components';

export const metadata: Metadata = {
  title: "Information Admin",
  description: "Generated by create next app",
};

export default async function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {

  const session = await auth();

  if ( !session?.user ) {
    redirect( '/auth/login' ); // Si no existe la sesión, redirigir a la página de login
  }

  return (
    <main className="flex justify-center">
      <Provider>
        { children }
      </Provider>
    </main>
  );
}
